### ISSUE TITLE
NaNs in fluxes at kstart and kend in moist thermo cases

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#109]
If I run `bomex` with the default settings, I notice NaNs on the two boundaries. I wanted to look at the odd `thv_flux` profiles we find sometimes, but then found that with the latest `main` the code fails in producing correct fluxes on the walls. It seems to be related to moist thermo, because `drycblles`  and the DNS cases are fine.

NaN's disappear if I switch the masks off.

**Comment by Chiil** [comment]
NaN's disappear if I switch the masks off.

**Comment by thijsheus** [comment]
related to [8479c171ec7c5b529010145e62e90d171d5a704b](https://github.com/microhh/microhh/commit/8479c171ec7c5b529010145e62e90d171d5a704b) and following commits

**Comment by julietbravo** [comment]
Hmm, we changed the flux stats because of issues with the masked statistics, but I will look into it tomorrow...

**Comment by Chiil** [comment]
`Subtract_mean` reads out of bounds and causes the code to crash with a segfault. Reverting the commit removes the segfault. The call on line 1472 gives `kend+1` as the end of the range and `Subtract_mean` adds another +1

**Comment by thijsheus** [comment]
Fixed by https://github.com/microhh/microhh/pull/125
