### ISSUE TITLE
cross_to_nc.py does not work out of the box

### ISSUE THREAD

**Issue by WBMol** [microhh/microhh#147]
Running `python cross_to_nc.py` in the run folder with cross sections `<var>.xy.<level>.<time>` gives the following error for the `drycblles` case (for every variable in the `ini`):

```bash
not enough values to unpack (expected 2, got 1)
Failed to create th.xy.nc
```

Which comes from line 52 in `cross_to_nc.py` where the `python/microhh_tools.py` function `get_cross_indices` is called.

This is the relevant section of my `drycblles.ini`: 

```ini
[cross]
swcross=1
crosslist=th,w
sampletime=1800
xy=0
```

For multiple `xy` levels, I get a different error. `ini`:

```ini
[cross]
swcross=1
crosslist=th,w
sampletime=1800
xy=0,100
```

Gives:
```bash
'int' object is not subscriptable
Failed to create th.xy.nc
'int' object is not subscriptable
Failed to create w.xy.nc
```

System information:
- Either Manjaro or MacOS
- Python 3.9 or 3.11
- Latest numpy (1.26.0) and netcdf4 (1.6.4)

**Comment by julietbravo** [comment]
It seems that `microhh_tools.py` is not updated for the changes in `cross_to_nc.py`; `get_cross_indices()` only returns the full levels, but `cross_to_nc.py` expects to get the full and half levels. @thijsheus, could it be that you forgot to commit the changes in `microhh_tools.py` when you fixed the half level problems?

**Comment by thijsheus** [comment]
I'll have a look - this was definitely working for me at some point. May have been a failed commit indeed :)
