### ISSUE TITLE
Error in automatic resubmission script

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#15]
In case the wall clock limit is hit, the resubmission script ends at a time that is not necessarily a save time and computing time gets lost.

**Comment by Chiil** [comment]
@julietbravo Is this script still alive, if not let's close this.

**Comment by julietbravo** [comment]
It is still in the repo: https://github.com/microhh/microhh/blob/main/misc/runscripts/run_restart.slurm

I personally replaced it with a Python version, so I don't use it anymore...

**Comment by Chiil** [comment]
OK, let's close this then since it is minor and not in use.
