### ISSUE TITLE
Improve Netcdf cross-sections and dumps

### ISSUE THREAD

**Issue by thijsheus** [microhh/microhh#152]
- [ ] Unlimited Time variable
- [ ] time-attribute called "seconds since" or something CF-compliant for easier plotting in Paraview, XArray, etc
- [ ] chunking algorithm

**Comment by julietbravo** [comment]
I noticed that on some systems, this step is extremely slow because of the `glob.glob` for each output time step. I still have to look into a better solution.

```
# Calculate the number of iterations
for time in np.arange(starttime, endtime, sampletime):
    otime = int(round(time / 10**iotimeprec))
    if not glob.glob('*.{0:07d}'.format(otime)):
        endtime = time - sampletime
        break
niter = int((endtime - starttime) / sampletime + 1)
```
