### ISSUE TITLE
Compatibility of budget statistics and spatial order

### ISSUE THREAD

**Issue by adconnolly** [microhh/microhh#165]
Budget::factory could check that if swbudget== "4" that swspatialorder == "4" (as the documentation correctly states it must) to prevent a later error when writing the budget statistics. I suggest modifying  the code currently at line 63 of buffer.cxx from
`    else if (swbudget == "4")`   
to
`    else if (swbudget == "4" && swspatialorder == "4")`
Where swspatial order is defined locally with
`std::string swspatialorder = inputin.get_item<std::string>("grid", "swspatialorder", "", "0");`
We can also add to the error message thrown in the else statement to direct users to check for this compatibility in their .ini file. 
I'm happy to make these changes to the cpu code, and already have on my local branch, but I am not familiar with the GPU versions. I also don't believe I have permission to contribute to this repo anyway, so I'll just leave this as an issue for the wider community.

**Comment by julietbravo** [comment]
We just had a discussion about that; I personally think it would make more sense to make the `swbudget` switch `true/false`, and then indeed select the correct one based on `swspatialorder`.

About contributions: we have a (very) short explanation here: https://github.com/microhh/microhh#contributing . The trick is to make a fork of MicroHH, commit the changes there, and then open a pull request at https://github.com/microhh/microhh/pulls

**Comment by adconnolly** [comment]
That solution would seem to fix the error that I encountered when swbudget=4 but swspatialorder=2, but I thought it was possible to have swbudget=2 while swspatialorder=4 so they need not be exactly the same order? If that is not possible, potentially the documentation is a little bit ambiguous as it only addresses the first case: "The switch swbudget can only be set to 4 if [grid] has swspatialorder=4."   
Thanks for the advice re contributions.

**Comment by julietbravo** [comment]
I personally can't think of a situation where you would like to use the 2nd order budget statistics with `swspatialorder=4`. @Chiil, what do you think?

**Comment by Chiil** [comment]
Nope, default to swspatialorder is perfect.On 10 Oct 2023, at 21:56, Bart van Stratum ***@***.***> wrote:﻿
I personally can't think of a situation where you would like to use the 2nd order budget statistics with swspatialorder=4. @Chiil, what do you think?
