### ISSUE TITLE
resolved flux for advec_2i5 at the wall has wiggle

### ISSUE THREAD

**Issue by thijsheus** [microhh/microhh#201]

**Comment by julietbravo** [comment]
The revert to the old absolute fluxes is in here: https://github.com/julietbravo/microhh/tree/main_flux_bug_fix

**Comment by thijsheus** [comment]
Looks good to me. Feel free to PR, merge it into Chiel's PR, or something in between.

**Comment by Chiil** [comment]
Old code has been restored.
