### ISSUE TITLE
Buoyancy flux budget terms at zh[kstart] are incorrect

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#21]
The discretization is correct in the statistics. The problem is that dp/dz is set to zero in the pressure solver. 

Furthermore, there is a bump in the viscous transport at zh[kstart+1] and an incorrect zero value at zh[kstart] due to the global conservation that is built into w.

**Comment by thijsheus** [comment]
Is this still the case?

**Comment by Chiil** [comment]
Nope, I close it.
