### ISSUE TITLE
Testing for 2.0 release (2024 version)

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#236]
Overview testing activities...

**Comment by julietbravo** [comment]
Eddy (RTX A5000):

- [x] `run_restart_set.py` gives no errors for `sp/dp + cpu/cpumpi/gpu/gpu_kl`.

**Comment by julietbravo** [comment]
Snellius (A100):

- [ ] `run_restart_set.py` has errors for:
    - Running case 'bomex' for executable '../build_dp_gpu/microhh' in dir 'dp_gpu_default_restart'
    - Running case 'bomex' for executable '../build_dp_gpu/microhh' in dir 'dp_gpu_deardorff_restart'
    - Running case 'rico' for executable '../build_dp_gpu/microhh' in dir 'dp_gpu_default_restart'
    - Running case 'bomex' for executable '../build_dp_gpu_kl/microhh' in dir 'dp_gpu_kl_default_restart'
    - Running case 'bomex' for executable '../build_dp_gpu_kl/microhh' in dir 'dp_gpu_kl_deardorff_restart'
    - Running case 'rico' for executable '../build_dp_gpu_kl/microhh' in dir 'dp_gpu_kl_default_restart'
    - Running case 'bomex' for executable '../build_sp_gpu/microhh' in dir 'sp_gpu_default_restart'
    - Running case 'bomex' for executable '../build_sp_gpu/microhh' in dir 'sp_gpu_deardorff_restart'
    - Running case 'bomex' for executable '../build_sp_gpu_kl/microhh' in dir 'sp_gpu_kl_default_restart'
    - Running case 'bomex' for executable '../build_sp_gpu_kl/microhh' in dir 'sp_gpu_kl_deardorff_restart'

**Comment by thijsheus** [comment]
On cumulus (V100), I get restart errors for (kernel launcher always on):
- Running case 'bomex' for executable '../build_dp_gpu/microhh' in dir 'dp_gpu_default_restart'
- Running case 'bomex' for executable '../build_dp_gpu/microhh' in dir 'dp_gpu_deardorff_restart'
- Running case 'bomex' for executable '../build_sp_gpu/microhh' in dir 'sp_gpu_deardorff_restart'

This starts to look like an actual bug to resolve

**Comment by Chiil** [comment]
Error traced down to the base state, fixing the base state makes all cases pass on all testing machines.

**Comment by Chiil** [comment]
I solved the issue in PR #261.
