### ISSUE TITLE
Inconsistent naming `timedep` radiation

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#239]
Most `timedep` options are named `swtimedep` or `swtimedep_bla` in the `.ini` file, including the newly added `swtimedep` for aerosols. However, in the radiation group, this option is named `swupdatecolumn`. For consistency, wouldn't it be better to name this `swtimedep` or  `swtimedep_background`? Since these options are very new (and probably have only been used by Mirjam and myself), I would prefer to change them before the 2.0 release. 

What do you think (including @MirjamTijhuis)?

**Comment by Chiil** [comment]
Please do so, no-one except for @MirjamTijhuis has used this.

**Comment by MirjamTijhuis** [comment]
That makes sense. I prefer `swtimedep_background` . I think it describes well what the thing is for, whereas a switch which is just called `swtimedep` could mean multiple things given all the options in the radiation group.

**Comment by julietbravo** [comment]
@MirjamTijhuis  I agree

**Comment by julietbravo** [comment]
Problem is fixed, forgot which commit, but see: https://github.com/microhh/microhh/blob/main/src/background_profs.cxx#L47
