### ISSUE TITLE
Don't default `nudgefac` to zero?

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#246]
Perhaps it is better to raise an exception if a user enables nudging, but does not provide `nudgefac` in the `case_input.nc` file? Right now, `nudgefac` will default to zero, essentially disabling nudging.

**Comment by thijsheus** [comment]
I can be on board with raising an exception; I don't however what a better default is for `nudgefac` other than 0.

**Comment by julietbravo** [comment]
Fixed by https://github.com/microhh/microhh/pull/263
