### ISSUE TITLE
Standard output prints incorrect value for x,xh,y,yh for cross sections

### ISSUE THREAD

**Issue by jeremygibbs** [microhh/microhh#26]
### Issue
On the yz_cross_sections branch, the [standard output](https://dl.dropboxusercontent.com/u/2575480/microhh_r.out) reports the wrong values sometimes for x, xh, y, yh - although the i and j spots are correct. Like this:
**Added XZ cross at y=514.000000 (j=256) for [cross][xz]=1024.000000**
**Added XZ cross at yh=634.000000 (j=256) for [cross][xz]=1024.000000**
**Added YZ cross at x=0.000000 (i=256) for [cross][yz]=1024.000000**
**Added YZ cross at xh=0.000000 (i=256) for [cross][yz]=1024.000000**

The cross section data is correctly named and the data seems reasonable. As a note, I never modified the printout calls in cross.cxx for XZ. I merely copied and modified those lines for YZ.

### Where/How
This only seems to happen on UCAR's Yellowstone cluster. I tried to reproduce on a local Mac using the same code and failed (the standard output was correct). Here are the relevant files: [configure](https://dl.dropboxusercontent.com/u/2575480/default.cmake), [ini](https://dl.dropboxusercontent.com/u/2575480/drycblslope.ini).

**Comment by Chiil** [comment]
Out of bounds read when the cross was not within the range of the first mpiid. Bug has been solved.
