### ISSUE TITLE
icc default! why not gcc default

### ISSUE THREAD

**Issue by rajeeja** [microhh/microhh#36]
Trying to set build on Ubuntu: It would be better to make gcc default?
CMake Error at /usr/share/cmake-3.5/Modules/CMakeDetermineCCompiler.cmake:57 (message):
  Could not find compiler set in environment variable CC:

  icc.
Call Stack (most recent call first):
  CMakeLists.txt:61 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/jain/microhh/build/CMakeFiles/CMakeOutput.log".

**Comment by Chiil** [comment]
I agree.  I changed it, give it a try.
