### ISSUE TITLE
ccmake or cmake NetCDF specification?

### ISSUE THREAD

**Issue by rajeeja** [microhh/microhh#37]
Thanks for the gcc fix. Another one: I have netcdf installed or so I think:
How do I specify it? ccmake .. didn't give me an option to specify NetCDF
===> which ncdump
/usr/bin/ncdump
jain@jain-VirtualBox:~/microhh/build[master]
===> ncdump -h
ncdump [-c|-h] [-v ...] [[-b|-f] [c|f]] [-l len] [-n name] [-p n[,n]] [-k] [-x] [-s] [-t|-i] [-g ...] [-w] file
  [-c]             Coordinate variable data and header information
  [-h]             Header information only, no data
  [-v var1[,...]]  Data for variable(s) <var1>,... only
  [-b [c|f]]       Brief annotations for C or Fortran indices in data
  [-f [c|f]]       Full annotations for C or Fortran indices in data
  [-l len]         Line length maximum in data section (default 80)
  [-n name]        Name for netCDF (default derived from file name)
  [-p n[,n]]       Display floating-point values with less precision
  [-k]             Output kind of netCDF file
  [-s]             Output special (virtual) attributes
  [-t]             Output time data as date-time strings
  [-i]             Output time data as date-time strings with ISO-8601 'T' separator
  [-g grp1[,...]]  Data and metadata for group(s) <grp1>,... only
  [-w]             With client-side caching of variables for DAP URLs
  [-x]             Output XML (NcML) instead of CDL
  file             Name of netCDF file (or URL if DAP access enabled)
netcdf library version 4.4.0 of Mar 29 2016 11:41:40 $

**Comment by rajeeja** [comment]
===> make
[  0%] Built target todo
[  2%] Building CXX object src/CMakeFiles/microhhc.dir/budget.cxx.o
In file included from /home/jain/microhh/src/budget.cxx:29:0:
/home/jain/microhh/src/../include/stats.h:27:18: fatal error: netcdf: No such file or directory
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:110: recipe for target 'src/CMakeFiles/microhhc.dir/budget.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/budget.cxx.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'src/CMakeFiles/microhhc.dir/all' failed
make[1]: *** [src/CMakeFiles/microhhc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Chiil** [comment]
If you are using the Ubuntu config, most likely your netcdf library is missing. Install the `libnetcdf-dev`, `libnetcdff-dev`, and `libnetcdf-c++4-dev` packages.

**Comment by rajeeja** [comment]
cool! that did the trick, was missing the c++4 one.
