### ISSUE TITLE
Possible GCC/ C+11 issue

### ISSUE THREAD

**Issue by rajeeja** [microhh/microhh#38]
Will this be supported: https://stackoverflow.com/questions/12975341/to-string-is-not-a-member-of-std-says-g-mingw

I'm on Ubuntu 16.04, not mingw, but the issue is similar: 

[ 42%] Building CXX object src/CMakeFiles/microhhc.dir/fields.cxx.o
/home/jain/microhh/src/fields.cxx: In member function ‘void Fields::init()’:
**/home/jain/microhh/src/fields.cxx:172:36: error: ‘to_string’ is not a member of ‘std’
         std::string name = "tmp" + std::to_string(static_cast<long long>(i));
                                    ^**
src/CMakeFiles/microhhc.dir/build.make:518: recipe for target 'src/CMakeFiles/microhhc.dir/fields.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/fields.cxx.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'src/CMakeFiles/microhhc.dir/all' failed
make[1]: *** [src/CMakeFiles/microhhc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
jain@jain-VirtualBox:~/microhh/build[master]
===> gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Chiil** [comment]
The ubuntu config was lacking the C++11 flag. Please check if it works now.

**Comment by Chiil** [comment]
Problem no longer exists.
