### ISSUE TITLE
fftw3 Ubuntu static file not found

### ISSUE THREAD

**Issue by rajeeja** [microhh/microhh#39]
I don't have /libfftw3.a ? Installed sudo apt-get install libfftw3-dev. See below:

 ===> l /usr/lib/libfftw
libfftw.a                 libfftw_mpi.so            libfftw_mpi.so.2.0.7      libfftw.so.2              libfftw_threads.a         libfftw_threads.so.2
libfftw_mpi.a             libfftw_mpi.so.2          libfftw.so                libfftw.so.2.0.7          libfftw_threads.so        libfftw_threads.so.2.0.7

Scanning dependencies of target microhh
[ 97%] Building CXX object main/CMakeFiles/microhh.dir/microhh.cxx.o
**make[2]: *** No rule to make target '/usr/lib/libfftw3.a', needed by 'microhh'.  Stop.**
CMakeFiles/Makefile2:177: recipe for target 'main/CMakeFiles/microhh.dir/all' failed
make[1]: *** [main/CMakeFiles/microhh.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have it installed:
===> sudo apt-get install libfftw3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libfftw3-dev is already the newest version (3.3.4-2ubuntu1).
The following packages were automatically installed and are no longer required:
  libcr-dev libhwloc-dev libibverbs-dev libnuma-dev linux-headers-4.10.0-30 linux-headers-4.10.0-30-generic linux-image-4.10.0-30-generic
  linux-image-extra-4.10.0-30-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 153 not upgraded.

Hopefully this is the final one:) Thanks for the replies.

**Comment by rajeeja** [comment]
Also, I don't seem to have /usr/lib/libnetcdf_c++.a

**Comment by rajeeja** [comment]
I have this: /usr/lib/x86_64-linux-gnu/libnetcdf_c++4.a

**Comment by Chiil** [comment]
Edit the `ubuntu.conf` with the correct library names and paths. Replace the name of the  NetCDF with the one you suggest, because the config file is referring to the old legacy C++. The ubuntu.conf file is quite old and none of the main developers at the moment is using ubuntu. Let me know if it works.

**Comment by Chiil** [comment]
I have prepared a ubuntu.conf that runs on 16.04.
