### ISSUE TITLE
Building Microhh on RHEL

### ISSUE THREAD

**Issue by manmeet3591** [microhh/microhh#42]
I am trying to build microhh on the HPC(Red Had Entereprise Linux) at my institute and I am getting the following error 

$ make -j
[ 97%] Built target microhhc
[ 97%] Built target todo
[100%] Building CXX object main/CMakeFiles/microhh.dir/microhh.cxx.o
/iitm2/cccr-res/msingh/microhh1.0/microhh/main/microhh.cxx:1: error: bad value (nativei) for -march= switch
make[2]: *** [main/CMakeFiles/microhh.dir/microhh.cxx.o] Error 1
make[1]: *** [main/CMakeFiles/microhh.dir/all] Error 2
make: *** [all] Error 2

while make as I followed the tutorial.

I found in https://stackoverflow.com/questions/35816920/unrecognized-command-line-option-std-c11 that one the build is doing it with g++ and it might be old so its not supporting std=c++11 and hence I changed the flags in flags.make to std=c++0x and another issue I was facing was with 
SEEK_SET, SEEK_END and SEEK_CUR 
According to the following page, its a known issue in MPI-2 and hence I added the flag  -DMPICH_IGNORE_CXX_SEEK as per 
https://software.intel.com/en-us/forums/intel-c-compiler/topic/560682 and the error went away. 

Now since the error its throwing is from inside the code, i am clueless as to what to do

**Comment by Chiil** [comment]
Most likely you have a typo in your `-march=native` statement and you glued an `i` to native, as your error message suggests: bad value *nativei*.

**Comment by manmeet3591** [comment]
Thanks. That is resolved now. 

But next when I am trying to compile following shows up
$ make -j
[ 95%] [ 97%] Built target todo
Built target microhhc
Linking CXX executable ../microhh
/usr/bin/ld: cannot find -lcurl
collect2: ld returned 1 exit status
make[2]: *** [microhh] Error 1
make[1]: *** [main/CMakeFiles/microhh.dir/all] Error 2
make: *** [all] Error 2

Now I am trying to find where that the path to the curl link is specified as /us/bin/ld 

Since I am on a common HPC, the location of my curl is at /usr/bin/curl
Can you please help me in knowing where to give the location of curl 

Thanks 
Manmeet

**Comment by manmeet3591** [comment]
I tried changing the curl in default.cmake file to /usr/bin/curl and I am getting the following error. 

/usr/bin/ld: error in /usr/bin/curl(.eh_frame); no .eh_frame_hdr table will be created.
/usr/bin/ld: error in /usr/bin/curl(.eh_frame); no .eh_frame_hdr table will be created.
/usr/bin/ld: warning: section `.bss' type changed to PROGBITS

**Comment by Chiil** [comment]
I think you need to point the libcurl in /usr/lib

**Comment by manmeet3591** [comment]
I have tried a lot but still unsuccessful. Can you please share a default.cmake for redhat.

I am using the following default.cmake
# Ubuntu 16.04
if(USEMPI)
  set(ENV{CC}  mpicc ) # C compiler for parallel build
  set(ENV{CXX} mpicxx) # C++ compiler for parallel build
else()
  set(ENV{CC}  gcc) # C compiler for serial build
  set(ENV{CXX} g++) # C++ compiler for serial build
endif()

set(USER_CXX_FLAGS "-std=c++0x -DMPICH_IGNORE_CXX_SEEK")
set(USER_CXX_FLAGS_RELEASE "-O3 -ffast-math -mtune=native -march=native")
set(USER_CXX_FLAGS_DEBUG "-O0 -g -Wall -Wno-unknown-pragmas")

set(FFTW_INCLUDE_DIR   "/gpfs1/home/Libs/GNU/FFTW-3.3.4/include")
set(FFTW_LIB           "/gpfs1/home/Libs/GNU/FFTW-3.3.4/lib/libfftw3.a")
set(NETCDF_INCLUDE_DIR "/iitm2/cccr-res/msingh/Libraries/netcdf-cxx-old/include")
set(NETCDF_LIB_C       "/iitm2/cccr-res/msingh/Libraries/netcdf-c/lib/libnetcdf.so")
set(NETCDF_LIB_CPP     "/iitm2/cccr-res/msingh/Libraries/netcdf-cxx-old/lib/libnetcdf_c++4.so")
set(HDF5_LIB_1         "/gpfs1/home/Libs/GNU/HDF5/hdf5-1.8.11/lib/libhdf5.so")
set(HDF5_LIB_2         "/gpfs1/home/Libs/GNU/HDF5/hdf5-1.8.11/lib/libhdf5_hl.so")
set(SZIP_LIB           "/gpfs1/home/Libs/GNU/SZIP/szip-2.1/lib/libsz.so")
set(CURL_LIB                                     "/usr/lib64/libcurl.so.4")
set(LIBS ${FFTW_LIB} ${NETCDF_LIB_CPP} ${NETCDF_LIB_C} ${HDF5_LIB_2} ${HDF5_LIB_1} ${SZIP_LIB} ${CURL_LIB} m z /usr/bin/curl)
set(INCLUDE_DIRS ${FFTW_INCLUDE_DIR} ${NETCDF_INCLUDE_DIR})

add_definitions(-DRESTRICTKEYWORD=__restrict__)

**Comment by julietbravo** [comment]
We don't have access to a RHEL system, so we can't make a cmake config file for that. Where exactly is the build failing at the moment?

**Comment by manmeet3591** [comment]
I tried using -std=c++11 but the build fails
The build is failing at make with the following error

$ make -j
[ 97%] Built target microhhc
Linking CXX executable ../microhh
[ 97%] Built target todo
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_start':
(.text+0x0): multiple definition of `_start'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.text+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o:(.fini+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.rodata+0x0): multiple definition of `_IO_stdin_used'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.rodata.cst4+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `__data_start':
(.data+0x0): multiple definition of `__data_start'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.data+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.rodata+0x8): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o:(.rodata+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_edata':
(*ABS*+0x61ce94): multiple definition of `__bss_start'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_end':
(*ABS*+0x61cf60): multiple definition of `_end'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_edata':
(*ABS*+0x61ce94): multiple definition of `_edata'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `main':
(.text+0x4a60): multiple definition of `main'
CMakeFiles/microhh.dir/microhh.cxx.o:microhh.cxx:(.text+0x30): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o:(.init+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `getpass_r':
(.text+0x8f10): multiple definition of `getpass_r'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x8f10): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `__libc_csu_fini':
(.text+0x94f0): multiple definition of `__libc_csu_fini'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x94f0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_start':
(.text+0x0): multiple definition of `_start'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.text+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `curlx_nonblock':
(.text+0x94a0): multiple definition of `curlx_nonblock'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x94a0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `hugehelp':
(.text+0x7b40): multiple definition of `hugehelp'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x7b40): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o:(.fini+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `cutil_tvnow':
(.text+0x90e0): multiple definition of `cutil_tvnow'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x90e0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `glob_url':
(.text+0x88a0): multiple definition of `glob_url'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x88a0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `glob_match_url':
(.text+0x7cf0): multiple definition of `glob_match_url'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x7cf0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `glob_cleanup':
(.text+0x7c20): multiple definition of `glob_cleanup'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x7c20): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.rodata+0x0): multiple definition of `_IO_stdin_used'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.rodata.cst4+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `__data_start':
(.data+0x0): multiple definition of `__data_start'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o:(.data+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `ourWriteOut':
(.text+0x89f0): multiple definition of `ourWriteOut'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x89f0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x0): multiple definition of `stdin@@GLIBC_2.2.5'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `Curl_raw_toupper':
(.text+0x9160): multiple definition of `Curl_raw_toupper'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9160): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.rodata+0x8): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o:(.rodata+0x0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.dtors+0x8): multiple definition of `__DTOR_END__'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.dtors+0x8): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `__libc_csu_init':
(.text+0x9500): multiple definition of `__libc_csu_init'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9500): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `Curl_strntoupper':
(.text+0x9460): multiple definition of `Curl_strntoupper'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9460): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `glob_next_url':
(.text+0x7f50): multiple definition of `glob_next_url'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x7f50): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_edata':
(*ABS*+0x61ce94): multiple definition of `__bss_start'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `cutil_tvdiff':
(.text+0x9080): multiple definition of `cutil_tvdiff'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9080): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `cutil_tvlong':
(.text+0x90d0): multiple definition of `cutil_tvlong'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x90d0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `homedir':
(.text+0x9020): multiple definition of `homedir'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9020): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_end':
(*ABS*+0x61cf60): multiple definition of `_end'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `Curl_raw_nequal':
(.text+0x93b0): multiple definition of `Curl_raw_nequal'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x93b0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x8): multiple definition of `stderr@@GLIBC_2.2.5'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x8): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_edata':
(*ABS*+0x61ce94): multiple definition of `_edata'
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `cutil_tvdiff_secs':
(.text+0x90b0): multiple definition of `cutil_tvdiff_secs'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x90b0): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `Curl_raw_equal':
(.text+0x9310): multiple definition of `Curl_raw_equal'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.text+0x9310): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x10): multiple definition of `stdout@@GLIBC_2.2.5'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.bss+0x10): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `main':
(.text+0x4a60): multiple definition of `main'
CMakeFiles/microhh.dir/microhh.cxx.o:microhh.cxx:(.text+0x30): first defined here
/gpfs1/home/Libs/GNU/CURL/bin/curl: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o:(.init+0x0): first defined here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtend.o:(.dtors+0x0): multiple definition of `__DTOR_END__'
/gpfs1/home/Libs/GNU/CURL/bin/curl:(.dtors+0x8): first defined here
/usr/bin/ld: warning: libnetcdf.so.7, needed by /iitm2/cccr-res/msingh/Libraries/netcdf-cxx-old/lib/libnetcdf_c++4.so, may conflict with libnetcdf.so.11
/usr/bin/ld: error in /gpfs1/home/Libs/GNU/CURL/bin/curl(.eh_frame); no .eh_frame_hdr table will be created.
/usr/bin/ld: error in /gpfs1/home/Libs/GNU/CURL/bin/curl(.eh_frame); no .eh_frame_hdr table will be created.
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::add_fixed_prof(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double*)':
stats.cxx:(.text+0x2d25): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x2d3a): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x2d4f): undefined reference to `NcVar::add_att(char const*, double)'
stats.cxx:(.text+0x2d91): undefined reference to `NcVar::put(double const*, long, long, long, long, long)'
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::add_time_series(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
stats.cxx:(.text+0x339c): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x34ec): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x361a): undefined reference to `NcVar::add_att(char const*, double)'
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::exec(int, double, unsigned long)':
stats.cxx:(.text+0x403b): undefined reference to `NcVar::put_rec(double const*, long)'
stats.cxx:(.text+0x404d): undefined reference to `NcVar::put_rec(int const*, long)'
stats.cxx:(.text+0x4267): undefined reference to `NcVar::put_rec(double const*, long)'
stats.cxx:(.text+0x4487): undefined reference to `NcVar::put_rec(double const*, long)'
stats.cxx:(.text+0x44a9): undefined reference to `NcFile::sync()'
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::add_prof(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
stats.cxx:(.text+0x4d98): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x4ed5): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x500a): undefined reference to `NcVar::add_att(char const*, double)'
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::create(int)':
stats.cxx:(.text+0x53d6): undefined reference to `NcFile::NcFile(char const*, NcFile::FileMode, unsigned long*, unsigned long, NcFile::FileFormat)'
stats.cxx:(.text+0x53e2): undefined reference to `NcFile::is_valid() const'
stats.cxx:(.text+0x54b5): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x54c8): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x550d): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x5520): undefined reference to `NcVar::add_att(char const*, char const*)'
stats.cxx:(.text+0x5564): undefined reference to `NcVar::add_att(char const*, char const*)'
../src/libmicrohhc.a(stats.cxx.o):stats.cxx:(.text+0x5576): more undefined references to `NcVar::add_att(char const*, char const*)' follow
../src/libmicrohhc.a(stats.cxx.o): In function `Stats::create(int)':
stats.cxx:(.text+0x55fb): undefined reference to `NcVar::put(double const*, long, long, long, long, long)'
stats.cxx:(.text+0x562f): undefined reference to `NcVar::put(double const*, long, long, long, long, long)'
stats.cxx:(.text+0x5638): undefined reference to `NcFile::sync()'
collect2: ld returned 1 exit status
make[2]: *** [microhh] Error 1
make[1]: *** [main/CMakeFiles/microhh.dir/all] Error 2
make: *** [all] Error 2

**Comment by manmeet3591** [comment]
I was trying to use a custom curl rather than the one that is used by default at the system at my institute and I guess its trying to say that this is an issue of multiple definition, but I am stuck at this for 2 days now

**Comment by julietbravo** [comment]
The first errors seem to be related to Curl, for this problem I think you should contact the system administrator or helpdesk. 

There are a lot of NetCDF related errors. Looking at your CMake config file, I see that you only provide the include directory of `NetCDF-cxx4`, there should also be one to the general (C) NetCDF library (please have a look at e.g. the `cartesius_netcdf4.cmake` file, which is a more suitable blueprint for a supercomputer config file than the Ubuntu one, and which covers these things).
