### ISSUE TITLE
Build error on iMac

### ISSUE THREAD

**Issue by KohinH** [microhh/microhh#44]
I'm trying to build microhh on my iMac but getting the following error

$cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-7
-- Check for working C compiler: /usr/local/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-7
-- Check for working CXX compiler: /usr/local/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MPI: Disabled.
-- CUDA: Disabled.
-- Build Type: RELEASE
-- Compiler flags: -std=c++11 -Ofast -march=native
-- Found Git: /usr/local/bin/git (found version "2.16.1") 
-- Git hash 1.6.0-178-gb4387903
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen dot 
-- Configuring done
-- Generating done
$make -j
.....
[ 97%] Building CXX object main/CMakeFiles/microhh.dir/microhh.cxx.o
[100%] Linking CXX executable ../microhh
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicrohhc.a(grid_parallel.cxx.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicrohhc.a(master_parallel.cxx.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicrohhc.a(grid_parallel.cxx.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicrohhc.a(master_parallel.cxx.o) has no symbols
Undefined symbols for architecture x86_64:
  "netCDF::NcFile::NcFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, netCDF::NcFile::FileMode)", referenced from:
      Stats::create(int)  in libmicrohhc.a(stats.cxx.o)
      Column::create(int)  in libmicrohhc.a(column.cxx.o)
.....
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [microhh] Error 1
make[1]: *** [main/CMakeFiles/microhh.dir/all] Error 2
make: *** [all] Error 2

Could you please help me solving this problem?
Thank you

**Comment by julietbravo** [comment]
Which NetCDF version did you install? You need the new NetCDF C++4 interface (https://github.com/Unidata/netcdf-cxx4) instead of the old NetCDF-C++ interface (not sure if that is the problem, just checking).

**Comment by KohinH** [comment]
I upgraded my netcdf to 4.6.1 but can not get rid of this error yet...

**Comment by julietbravo** [comment]
Can you check whether the NetCDF library and include paths that you specify in your CMake config file actually exist on your system? These three, which are set in `config/default.cmake` (or any other CMake file that you use):

    NETCDF_INCLUDE_DIR
    NETCDF_LIB_C
    NETCDF_LIB_CPP

**Comment by KohinH** [comment]
Thanks julietbravo. The problem is solved. The brew installed NetCDF interface was good. I'm not sure where the problem comes from, but it was fixed after I updated to OS10.13.4 and reinstalled Xcode and Command Line Tools.
