### ISSUE TITLE
Segfault 11 on gabls1, arm, drycblles with swstats

### ISSUE THREAD

**Issue by StevenvdLinden** [microhh/microhh#46]
Standard cases gabls1, arm, drycblles result in segmentation fault 11, when statistics switch is set to 1. 
Setting statistics off does not result in this error.

**Comment by julietbravo** [comment]
Just to be sure: did you checkout the last master version? I recently (https://github.com/microhh/microhh/commit/4d08895976402c9635afbeac377e616c02473022) fixed a similar bug, and for me the master runs fine with e.g. GABLS1

**Comment by julietbravo** [comment]
Not sure if we are looking at the same commit; the one I was referring to only initialises the `dataFile` pointer at zero to prevent segfaults. I would guess that all cases with `swstats=1` and `swcolumn=0` should have crashed, but I didn't check all of them....

**Comment by StevenvdLinden** [comment]
I was using an older 'version' of microhh that didn't have column.cxx, or any related functions included. In this case, setting swstats = 1 results in crashes for, e.g., gabls1, arm; but not for other les cases. I could not find a reason why some of these cases would be inherently different than others.
What was the reason for including the column-functionality?

**Comment by Chiil** [comment]
The column is like a radiosounding functionality. It is a single column save at a certain xy location. It does not replace the stats. The current master should run fine.

**Comment by julietbravo** [comment]
@StevenvdLinden, can I close this?

**Comment by StevenvdLinden** [comment]
No problem, I switched to the newest master-version and the issue is resolved.
Still, no idea why it crashed under the older version though.

On 4 Jun 2018, at 16:50, Bart van Stratum <notifications@github.com<mailto:notifications@github.com>> wrote:


@StevenvdLinden<https://github.com/StevenvdLinden>, can I close this?
