### ISSUE TITLE
RCEMIP statistics 

### ISSUE THREAD

**Issue by WBMol** [microhh/microhh#48]
For a full list of 1,2 and 3-D statistics required as output for RCMIP, see tables 4-7 [in the paper](https://www.geosci-model-dev.net/11/793/2018/gmd-11-793-2018-discussion.html).

For now though, the following set of statistics would be nice to have.

**domain averaged (t, z)**

- turbulent flux of virtual potential temperature
- relative humidity

**2-D instantaneous (x, y, t)**

- _fmse_, mass-weighted vertical integral of frozen moist static energy
- _hadvfmse_, mass-weighted vertical integral of horizontal advective tendency of frozen moist statis energy
- _vadvfmse_, mass-weighted vertical integral of vertical advective tendency of frozen moist static energy
- _tnfmse_, total tendency of mass-weighted vertical integral of frozen moist static energy
- _tnfmsevar_, total tendency of spatial variance of mass-weighted vertical integral of frozen moist static energy

**Comment by Chiil** [comment]
All stats implemented, results are submitted.
