### ISSUE TITLE
netcdf include compile error Ubuntu

### ISSUE THREAD

**Issue by davidrandell84** [microhh/microhh#49]
I'm having an issue compiling the code on ubuntu

I'm getting lots of netcdf errors:
netcdf: No such file or directory
 #include <netcdf>

I'm pretty sure I've got netcdf and netcdf-cxx libraries installed. I've also tried to mess around with the config/cmake file to get the paths right to no avail. Any help/insights would be appreciated. 

~/Documents/microhh/microhh/build$ ls /usr/lib/x86_64-linux-gnu/libnetcdf*
/usr/lib/x86_64-linux-gnu/libnetcdf_c++4.so.1
/usr/lib/x86_64-linux-gnu/libnetcdf_c++4.so.1.0.3
/usr/lib/x86_64-linux-gnu/libnetcdf_c++.a
/usr/lib/x86_64-linux-gnu/libnetcdf_c++.so
/usr/lib/x86_64-linux-gnu/libnetcdf_c++.so.4
/usr/lib/x86_64-linux-gnu/libnetcdf_c++.so.4.2.0
/usr/lib/x86_64-linux-gnu/libnetcdf.settings
/usr/lib/x86_64-linux-gnu/libnetcdf.so
/usr/lib/x86_64-linux-gnu/libnetcdf.so.13

Full log:

[  2%] Building CXX object src/CMakeFiles/microhhc.dir/boundary_surface.cxx.o
[ 24%] Building CXX object src/CMakeFiles/microhhc.dir/stats.cxx.o
[  4%] Building CXX object src/CMakeFiles/microhhc.dir/boundary_patch.cxx.o
[  6%] Building CXX object src/CMakeFiles/microhhc.dir/budget_2.cxx.o
[  8%] Building CXX object src/CMakeFiles/microhhc.dir/budget.cxx.o
[ 10%] Building CXX object src/CMakeFiles/microhhc.dir/diff_smag2.cxx.o
[ 12%] Building CXX object src/CMakeFiles/microhhc.dir/budget_4.cxx.o
[ 14%] Building CXX object src/CMakeFiles/microhhc.dir/boundary_surface_patch.cxx.o
[ 16%] Building CXX object src/CMakeFiles/microhhc.dir/boundary.cxx.o
[ 18%] Building CXX object src/CMakeFiles/microhhc.dir/thermo_dry.cxx.o
[ 20%] Building CXX object src/CMakeFiles/microhhc.dir/boundary_surface_bulk.cxx.o
[ 22%] Building CXX object src/CMakeFiles/microhhc.dir/column.cxx.o
[ 26%] Building CXX object src/CMakeFiles/microhhc.dir/cross.cxx.o
[ 28%] Building CXX object src/CMakeFiles/microhhc.dir/fields.cxx.o
[ 30%] Building CXX object src/CMakeFiles/microhhc.dir/model.cxx.o
[ 34%] Building CXX object src/CMakeFiles/microhhc.dir/thermo_vapor.cxx.o
[ 32%] Building CXX object src/CMakeFiles/microhhc.dir/thermo_moist.cxx.o
[ 34%] Built target todo
In file included from /home/davidrandell/Documents/microhh/microhh/src/budget.cxx:29:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:326: recipe for target 'src/CMakeFiles/microhhc.dir/budget.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/budget.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface.h:27:0,
                 from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface_patch.h:26,
                 from /home/davidrandell/Documents/microhh/microhh/src/boundary_surface_patch.cxx:29:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:302: recipe for target 'src/CMakeFiles/microhhc.dir/boundary_surface_patch.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/boundary_surface_patch.cxx.o] Error 1
/home/davidrandell/Documents/microhh/microhh/src/thermo_moist.cxx:28:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
In file included from /home/davidrandell/Documents/microhh/microhh/src/budget_4.cxx:32:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
In file included from /home/davidrandell/Documents/microhh/microhh/src/boundary_patch.cxx:33:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
/home/davidrandell/Documents/microhh/microhh/src/thermo_vapor.cxx:28:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:1094: recipe for target 'src/CMakeFiles/microhhc.dir/thermo_moist.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/thermo_moist.cxx.o] Error 1
src/CMakeFiles/microhhc.dir/build.make:1118: recipe for target 'src/CMakeFiles/microhhc.dir/thermo_vapor.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/thermo_vapor.cxx.o] Error 1
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:230: recipe for target 'src/CMakeFiles/microhhc.dir/boundary_patch.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/boundary_patch.cxx.o] Error 1
In file included from /home/davidrandell/Documents/microhh/microhh/src/budget_2.cxx:35:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
In file included from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface.h:27:0,
                 from /home/davidrandell/Documents/microhh/microhh/src/boundary_surface.cxx:31:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:254: recipe for target 'src/CMakeFiles/microhhc.dir/boundary_surface.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/boundary_surface.cxx.o] Error 1
In file included from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface.h:27:0,
                 from /home/davidrandell/Documents/microhh/microhh/src/diff_smag2.cxx:30:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
In file included from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface.h:27:0,
                 from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface_bulk.h:26,
                 from /home/davidrandell/Documents/microhh/microhh/src/boundary_surface_bulk.cxx:31:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:278: recipe for target 'src/CMakeFiles/microhhc.dir/boundary_surface_bulk.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/boundary_surface_bulk.cxx.o] Error 1
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:590: recipe for target 'src/CMakeFiles/microhhc.dir/diff_smag2.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/diff_smag2.cxx.o] Error 1
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:350: recipe for target 'src/CMakeFiles/microhhc.dir/budget_2.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/budget_2.cxx.o] Error 1
src/CMakeFiles/microhhc.dir/build.make:374: recipe for target 'src/CMakeFiles/microhhc.dir/budget_4.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/budget_4.cxx.o] Error 1
In file included from /home/davidrandell/Documents/microhh/microhh/src/column.cxx:31:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/column.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
In file included from /home/davidrandell/Documents/microhh/microhh/src/stats.cxx:31:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:446: recipe for target 'src/CMakeFiles/microhhc.dir/column.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/column.cxx.o] Error 1
src/CMakeFiles/microhhc.dir/build.make:974: recipe for target 'src/CMakeFiles/microhhc.dir/stats.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/stats.cxx.o] Error 1
In file included from /home/davidrandell/Documents/microhh/microhh/src/../include/boundary_surface.h:27:0,
                 from /home/davidrandell/Documents/microhh/microhh/src/boundary.cxx:37:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:206: recipe for target 'src/CMakeFiles/microhhc.dir/boundary.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/boundary.cxx.o] Error 1
/home/davidrandell/Documents/microhh/microhh/src/cross.cxx:37:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
In file included from /home/davidrandell/Documents/microhh/microhh/src/model.cxx:40:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:878: recipe for target 'src/CMakeFiles/microhhc.dir/model.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/model.cxx.o] Error 1
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:470: recipe for target 'src/CMakeFiles/microhhc.dir/cross.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/cross.cxx.o] Error 1
In file included from /home/davidrandell/Documents/microhh/microhh/src/thermo_dry.cxx:33:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
In file included from /home/davidrandell/Documents/microhh/microhh/src/fields.cxx:34:0:
/home/davidrandell/Documents/microhh/microhh/src/../include/stats.h:27:10: fatal error: netcdf: No such file or directory
 #include <netcdf>
          ^~~~~~~~
compilation terminated.
compilation terminated.
src/CMakeFiles/microhhc.dir/build.make:662: recipe for target 'src/CMakeFiles/microhhc.dir/fields.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/fields.cxx.o] Error 1
src/CMakeFiles/microhhc.dir/build.make:1070: recipe for target 'src/CMakeFiles/microhhc.dir/thermo_dry.cxx.o' failed
make[2]: *** [src/CMakeFiles/microhhc.dir/thermo_dry.cxx.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'src/CMakeFiles/microhhc.dir/all' failed
make[1]: *** [src/CMakeFiles/microhhc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Chiil** [comment]
Hi David,

You miss the 
libnetcdf-c++4-dev

package. Probably you have installed the legacy c++ package

Chiel

**Comment by julietbravo** [comment]
Did you use the default `ubuntu.config` file, or did you update the `NETCDF_LIB_CPP` in that file? Your NetCDF4 library is named `libnetcdf_c++4.so.1`, the one in the config file `libnetcdf_c++4.so`.

**Comment by davidrandell84** [comment]
Chiel, you are absolutely right I managed to install the legay c++ package. It has compiled now for me

Thanks for the quick response
