### ISSUE TITLE
Mistake/confusion in grid description

### ISSUE THREAD

**Issue by StevenvdLinden** [microhh/microhh#54]
The grid header `grid.h` states that `dz`  and `dzh` are the distances between the grid centers and the grid faces, respectively. However, these are not correct as `dz` is calculated in `grid.cxx` as the distance between the faces, and `dzh` the spacing between the centers. 
Therefore, the grid description should be updated accordingly, for example, `dz[k]` is the height of the cell centered around `z[k]` or something similar.

**Comment by julietbravo** [comment]
Someone seems to have fixed this, so I'll close the issue.

    std::vector<TF> dz;    // Distance between the faces of two grid cells in the z-direction.
    std::vector<TF> dzh;   // Distance between the centers of two grid cells in the z-direction.
