### ISSUE TITLE
FFTW_EXHAUSTIVE results in non bitwise identical restarts

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#60]
Despite the saving and loading of the plans, FFTW does not result in bitwise identical restarts is `FFTW_PATIENT` or `FFTW_EXHAUSTIVE` is chosen as the mode. I have reverted the setting to `FFTW_ESTIMATE` at the expense of a little performance.

**Comment by thijsheus** [comment]
Whether FFTW_EXHAUSTIVE was the culprit or not, the current version seems to work and be efficient. Closing.
