### ISSUE TITLE
Finish develop branch for 2.0 release

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#71]
**GPU:**
- [x] Implement new SL solver (BvS)
- [x] Implement LSM (BvS)
- [x] Fix CUDA compilation
    - [x] New subsidence options
    - [X] In/outflow BCs
    - [x] Uninitialized field in `Soil_grid` <- BvS: I can't reproduce this with valgrind/compute-sanitizer.
    - [x] `set_bc_g` in `boundary.cu` should be templated, just like the CPU version. 
- [X] Scalar outflow BCs (CvH)
- [X] Plumes (CvH)
- [x] Port new advection schemes (`2i53` currently missing) <-- delete `2i53`?
- [x] Delete thermo_vapor
- [X] Some `timedep` things are missing in `boundary.cu`.
- [x] Time varying outflow is missing (https://github.com/microhh/microhh/pull/131)
- [x] Merge Kernel Tuner <-- work in progress BvS
- [x] Include Deardorff SFS
- [x] Cleanup GPU in `boundary_surface_lsm`; lots of `cudaFree()`'s missing.
- [x] subsidence of momentum.
- [x] `boundary_surface` combined with heterogeneous z0's.

**General:**
- [x] Implement LSM
- [x] Cleanup wild growth of advection schemes
- [x] Introduce monotonic scheme combined with `2i3` and/or `2i4`
- [x] Import RTE+RRTMGP via `git submodule` (CvH)
- [x] Thoroughly check microphysics to pinpoint reason for difference with RICO paper in CC and Precip ***
- [x] Clean up scalar outflow BCs
- [x] Coupling radiation - LSM (emissivity, ...)
- [x] Coupling radiation - microphysics (https://github.com/microhh/microhh/issues/66) <- NOTE BvS: with the current solution, it is not possible to use radiation without microphysics, as `microphys_disabled` cannot provide e.g. `Nc0`. Fixed by https://github.com/microhh/microhh/pull/155
- [ ] Ni0 is hardcoded in `nsw6`
- [x] Add time varying solar constant
- [x] Consistent calculation du/dz: now differs between `boundary_surface` and `boundary_surface_bulk`.
- [x] Check consistency variable names (e.g. `qlpath` in cross vs `ql_path` in statistics).
- [x] The `sw_homogenize_xx` functions are commented out for SW and LW in rrtmgp.cxx?
- [x] Documentation
- [x] Clean up the issues list; either close, fix, wontfix, or assign a milestone.
- [x] Include/update file headers for copyright
- [x] Check `rrtmgp_rt` default settings (like `swalwaysrt`, which currently defaults to false). Fixed by https://github.com/microhh/microhh/pull/154

*** Note BvS: this is thoroughly checked in `develop_sb06`. If we switch to Axel's new implicit scheme in the future (also for warm microphysics), this will automatically enter the code. 

**Bugs:**
- [x] Radiation in the column statistics is zero after restart
- [x] NetCDF/HDF is not thread safe, this sometimes causes errors when saving the columns at a higher freq. than the stats.
- [x] `thv_flux` in statistics is (sometimes?) nonsense... 
- [x] CPU warm microphysics assumes that ice is liquid water (i.e. retrieves `ql_qi` from thermo), but the GPU version does not..
- [x] `2mom_warm` micro explodes in SP on the GPU (seems like a sedimentation issue).
- [x] https://github.com/microhh/microhh/issues/109
- [x] https://github.com/microhh/microhh/issues/78
- [x] https://github.com/microhh/microhh/issues/69
- [x] https://github.com/microhh/microhh/issues/43
- [x] `andren` case fails on GPU with illegal memory access in pressure solver.
- [x] nudge `timedep` leaks on GPU. (https://github.com/microhh/microhh/pull/135)
- [x] https://github.com/microhh/microhh/pull/157
- [x] `rrtmgp_rt` still expects `lat/lon` to be in the `[radiation]` group. Fixed by https://github.com/microhh/microhh/pull/154
- [x] `rrtmgp_rt` should check if the vertical grid is equidistant. Fixed by https://github.com/microhh/microhh/pull/154
- [x] https://github.com/microhh/microhh/issues/171
- [x] https://github.com/microhh/microhh/issues/192
- [x] https://github.com/microhh/microhh/issues/204
- [x] https://github.com/microhh/microhh/issues/205

**Misc:**
- [x] 2D tmp fields would be very useful...
- [x] `cross_to_nc.py` doesn't handle half level fields correctly (or top of domain fields at all...)
- [x] crosssections don't include offsets
- [x] Make `swupdatebasestate=true` default?

**Small stuff:**
- [x] Update readme Cabauw case; fix references, and remove microhh specific branches. Should all work with `main` now. <- BvS fixed in PR Mirjam
- [x] Check other cases for changed ini settings; e.g. subsidence name moved to local/global
- [x] Decide on some sane defaults; are local subsidence and fixed solar zenith really the expected values?
- [x] Check code for tabs, already found a few in e.g. radiation. <- BvS fixed in PR Mirjam.

**Comment by thijsheus** [comment]
Let's use this one as the full todo list for 2.0. Is this list up to date?

**Comment by julietbravo** [comment]
Yes

**Comment by julietbravo** [comment]
I moved the left over issues/improvement to a new 2.1 milestone issue.
