### ISSUE TITLE
Snellius notes

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#73]
NOTE: v1.0 of the documentation is online: https://microhh.readthedocs.io/en/latest/computing_systems/snellius.html#
----------------

A place to collect notes about the new SURF supercomputer.

### EasyBuild + NetCDF/Intel

NetCDF + Intel is not provided by SURF, and users need to compile it themselves. This is easy with EasyBuild:

    module load 2021
    module load eb/4.4.2
    eb -S netcdf

Results in a large list of NetCDF versions and compilers, incl. NetCDF 4.8.0 with Intel MPI, which can be compiled using:

    eblocalinstall netCDF-4.8.0-iimpi-2021a.eb

Afterwards the package is available like normal packages, but installed/compiled in your home directory:

    --------------------------- /home/bstratum/.local/easybuild/Centos8/2021/modulefiles/all ---------------------------
    netCDF/4.8.0-iimpi-2021a

### Ncview

Unfortunately there is no EasyBuild config for `ncview`, so I created one:

    ##
    # This file is an EasyBuild reciPY as per https://github.com/easybuilders/easybuild
    ##
    easyblock = 'ConfigureMake'
    
    name = 'ncview'
    version = '2.1.8'
    
    homepage = 'http://meteora.ucsd.edu/~pierce/ncview_home_page.html'
    description = """Ncview is a visual browser for netCDF format files. 
    Typically you would use ncview to get a quick and easy, push-button 
    look at your netCDF files. You can view simple movies of the data, 
    view along various dimensions, take a look at the actual data values, 
    change color maps, invert the data, etc."""
    
    toolchain = {'name': 'gompi', 'version': '2021a'}
    toolchainopts = {'usempi': True, 'pic': True}
    
    source_urls = ['ftp://cirrus.ucsd.edu/pub/ncview/']
    sources = [SOURCE_TAR_GZ]
    checksums = ['e8badc507b9b774801288d1c2d59eb79ab31b004df4858d0674ed0d87dfc91be']
    
    # specified compiler is hard checked against (full path to) compiler used for netCDF...
    preconfigopts = "CC=$(which $CC) "
    configopts = "--with-udunits2_incdir=$EBROOTUDUNITS/include --with-udunits2_libdir=$EBROOTUDUNITS/lib "
    configopts += "--with-nc-config=$EBROOTNETCDF/bin/nc-config"
    
    dependencies = [
        ('netCDF', '4.8.0'),
        ('netCDF-Fortran', '4.5.3'),
        ('UDUNITS', '2.2.28'),
        ('X11', '20210518'),
        ('libpng', '1.6.37'),
        ('zlib', '1.2.11'),
    ]
    
    sanity_check_paths = {
        'files': ['bin/ncview'],
        'dirs': [],
    }
    
    moduleclass = 'vis'

Assuming you called the script `ncview-2.1.8-gompi-2021a.eb`, compiling it is again the same trick:

    eblocalinstall ncview-2.1.8-gompi-2021a.eb

**Comment by julietbravo** [comment]
## Compiling MicroHH

The `snellius.cmake` config file has a switch at the top to switch between Intel and GCC. At the moment, parallel runs with Intel are a bit unstable, and large runs tend to crash with MPI errors. GCC works fine, but is a bit (~10%) slower.

### GCC modules
    module purge
    module load 2021
    module load CMake/3.20.1-GCCcore-10.3.0
    module load foss/2021a
    module load netCDF/4.8.0-gompi-2021a
    module load CUDA/11.3.1  <--- only needed for CUDA :-)

### Intel modules:
    module purge
    module load 2021
    module load CMake/3.20.1-GCCcore-10.3.0
    module load intel/2021a
    module load netCDF/4.8.0-iimpi-2021a
    module load FFTW/3.3.9-intel-2021a

**Comment by julietbravo** [comment]
### Example runscript

    #!/bin/bash
    #SBATCH --job-name=rico
    #SBATCH --output=mhh-%j.out
    #SBATCH --error=mhh-%j.err
    #SBATCH --partition=thin
    #SBATCH -n 128
    #SBATCH --cpus-per-task=1
    #SBATCH --ntasks-per-core=1
    #SBATCH -t 01:00:00
    
    module purge
    module load 2021
    module load CMake/3.20.1-GCCcore-10.3.0

    # For Intel:
    #module load intel/2021a
    #module load module load netCDF/4.8.0-iimpi-2021a
    #module load FFTW/3.3.9-intel-2021a
    
    # For GCC:
    module load foss/2021a
    module load netCDF/4.8.0-gompi-2021a
    
    srun ./microhh init rico
    srun ./microhh run rico

**Comment by julietbravo** [comment]
For playing around with (or development of) the GPU version, you can reserve a node interactively with:

    salloc --nodes 1 --ntasks 1 --cpus-per-task 18 -p gpu --time 01:00:00 --gpus=1

**Comment by Chiil** [comment]
Future usage of multi-GPU requires a local install of OpenMPI, which can be done with:

```
module load 2021
module load eb/4.5.1
module load PMIx/3.2.3-GCCcore-10.3.0
eblocalinstall OpenMPI-4.1.1-GCC-10.3.0-CUDA-11.3.1.eb
```

In order to make this work in Julia, load also `JULIA_CUDA_MEMORY_POOL = none` and use system MPI + CUDA.

**Comment by julietbravo** [comment]
Installing MUST (https://www.i12.rwth-aachen.de/go/id/nrbe).

    module purge
    module load eb/4.7.0
    eblocalinstall /sw/noarch/Centos8/2021/software/EasyBuild/4.7.0/easybuild/easyconfigs/m/MUST/MUST-1.7.2-foss-2021a.eb

**Comment by julietbravo** [comment]
Most of this is included in the documentation or outdated...
