### ISSUE TITLE
`cpu_up_to_date` issues with diagnostic fields.

### ISSUE THREAD

**Issue by julietbravo** [microhh/microhh#78]
The `cpu_up_to_date` flag for avoiding unnecessary copies from device to host is not completely foolproof. For example, at a statistics time, `setup_stats()` syncs the device to host and sets `cpu_up_to_date=true`, and the fields are not synced again before `calculate_statistics()`. However, this means that some diagnostic fields (like e.g. `ustar`, `obuk`, the base state variables, and microphysics rain rates) are not up-to-date in the statistics...

**Comment by thijsheus** [comment]
Seems to have been fixed by https://github.com/microhh/microhh/commit/65f0931159ed82160ceddd8bfb24b8b320b7091f
